// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ts23_dash_03

#include <stdio.h>
#include "backend.hpp"
#include "../ui.h"

void gauge_update_task(lv_timer_t * timer);
void motor_text(int temp, lv_obj_t *label, lv_obj_t *panel);
/* -------------------------------------------------------------------------- */
/*                              STATIC FUNCTIONS                              */
/* -------------------------------------------------------------------------- */
void gauge_update_task(lv_timer_t * timer)
{
    /*Static variable to save the previous value*/
    static VehicleState		    vehicle_state;
    static MotorInfo		    motor_info;
    static MiscInfo			    misc_info;
    static float max_power      = 0;
    static uint8_t max_speed    = 0;

    VehicleState    new_vehicle_state  = can_get_vehicle_state();
    MotorInfo       new_motor_info     = can_get_motor_info();
    MiscInfo        new_misc_info      = can_get_misc_info();

    /* -------------------------------- Motor Temps -------------------------------- */
    // TODO - Add separate motor temps
    if (motor_info.motor_temp != new_motor_info.motor_temp)
    {
        motor_info.motor_temp = new_motor_info.motor_temp;
        motor_text(motor_info.motor_temp, ui_MotorFrontLeft, ui_MotorFrontLeftPanel);
        motor_text(motor_info.motor_temp, ui_MotorFrontRight, ui_MotorFrontRightPanel);
        motor_text(motor_info.motor_temp, ui_MotorBackLeft, ui_MotorBackLeftPanel);
        motor_text(motor_info.motor_temp, ui_MotorBackRight, ui_MotorBackRightPanel);
    }

    /* ------------------------------- Speed ------------------------------- */
    if (misc_info.live_speed != new_misc_info.live_speed)
    {
        misc_info.live_speed = new_misc_info.live_speed;
        char speed_str[20];
        sprintf(speed_str, "%d km/h", misc_info.live_speed);
        lv_label_set_text(ui_MotorSpeedString, speed_str);
        // TODO - Connect driver and diagnostics stats
    }
    /* ---------------------------- Main gauge update --------------------------- */
    // TODO - Add brake and throttle to driver screen
    // if (misc_info.throttle_pct != new_misc_info.throttle_pct)
    // {
    //     misc_info.throttle_pct = new_misc_info.throttle_pct;
    //     lv_arc_set_value(ui_main_gauge,misc_info.throttle_pct);
    // }

    // if (misc_info.brake_pct != new_misc_info.brake_pct)
    // {
    //     misc_info.brake_pct = new_misc_info.brake_pct;
    //     lv_arc_set_value(ui_brake_arc,100-misc_info.brake_pct); //invert the value
    // }

    /* Update warning and LATCH errors */
    if (new_vehicle_state.precharge_pressed) 
    {
        lv_obj_clear_flag(ui_DriverLightUp, LV_OBJ_FLAG_HIDDEN);
    } 
    else if (new_vehicle_state.drive_pressed) 
        {
            lv_obj_add_flag(ui_DriverLightUp, LV_OBJ_FLAG_HIDDEN);
        } 
        else 
        {
            lv_obj_clear_flag(ui_DriverLightUp, LV_OBJ_FLAG_HIDDEN);
        }
    
    if (new_vehicle_state.trailbraking_active)
    {
        lv_obj_clear_flag(ui_DriverLightUp, LV_OBJ_FLAG_HIDDEN);
    }
    else {
        lv_obj_add_flag(ui_DriverLightUp, LV_OBJ_FLAG_HIDDEN);
    }

    // TODO - add error state
    // if (new_vehicle_state.error_ams) {
    //     show_AMS_error(critical_error,new_vehicle_state.error_ams);
    // } 
       
    // if (new_vehicle_state.error_bspd) {
    //     show_BSPD_error(critical_error);
    // }

    // if (new_vehicle_state.error_imd) {
    //     show_IMD_error(critical_error);
    // }

    // if (new_vehicle_state.error_pdoc_precharge) {
    //     show_PDOC_error(critical_error,0);
    // }

    // if (new_vehicle_state.error_pdoc_discharge) {
    //     show_PDOC_error(critical_error,1);
    // }
}

void motor_text(int temp, lv_obj_t *label, lv_obj_t *panel)
{
    char motor_str[20];

    if (temp <= 40)
    {
        sprintf(motor_str, "%d", temp);
        lv_obj_set_style_bg_color(panel, lv_color_hex(0x2D4467), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else if (temp <= 80)
    {
        sprintf(motor_str, "%d", temp);
        lv_obj_set_style_bg_color(panel, lv_color_hex(0xD27600), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else 
    {
        sprintf(motor_str, "%d", temp);
        lv_obj_set_style_bg_color(panel, lv_color_hex(0xA00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    lv_label_set_text(label, motor_str);
}

void ui_Driver_screen_init(void)
{
    ui_Driver = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Driver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MotorFrontLeftPanel = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_MotorFrontLeftPanel, 200);
    lv_obj_set_height(ui_MotorFrontLeftPanel, 140);
    lv_obj_set_x(ui_MotorFrontLeftPanel, -4);
    lv_obj_set_y(ui_MotorFrontLeftPanel, -4);
    lv_obj_clear_flag(ui_MotorFrontLeftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorFrontLeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorFrontLeftPanel, lv_color_hex(0xA00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorFrontLeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorFrontLeftPanel, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorFrontLeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorFrontLeft = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_MotorFrontLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorFrontLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorFrontLeft, 55);
    lv_obj_set_y(ui_MotorFrontLeft, 40);
    lv_label_set_text(ui_MotorFrontLeft, "80");
    lv_obj_set_style_text_font(ui_MotorFrontLeft, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorFrontRightPanel = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_MotorFrontRightPanel, 200);
    lv_obj_set_height(ui_MotorFrontRightPanel, 140);
    lv_obj_set_x(ui_MotorFrontRightPanel, 4);
    lv_obj_set_y(ui_MotorFrontRightPanel, -4);
    lv_obj_set_align(ui_MotorFrontRightPanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_MotorFrontRightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorFrontRightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorFrontRightPanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorFrontRightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorFrontRightPanel, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorFrontRightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorFrontRight = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_MotorFrontRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorFrontRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorFrontRight, -55);
    lv_obj_set_y(ui_MotorFrontRight, 40);
    lv_obj_set_align(ui_MotorFrontRight, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_MotorFrontRight, "100");
    lv_obj_set_style_text_font(ui_MotorFrontRight, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorBackLeftPanel = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_MotorBackLeftPanel, 200);
    lv_obj_set_height(ui_MotorBackLeftPanel, 140);
    lv_obj_set_x(ui_MotorBackLeftPanel, -4);
    lv_obj_set_y(ui_MotorBackLeftPanel, 4);
    lv_obj_set_align(ui_MotorBackLeftPanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_MotorBackLeftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorBackLeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorBackLeftPanel, lv_color_hex(0xD27600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorBackLeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorBackLeftPanel, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorBackLeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorBackLeft = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_MotorBackLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorBackLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorBackLeft, 55);
    lv_obj_set_y(ui_MotorBackLeft, -40);
    lv_obj_set_align(ui_MotorBackLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_MotorBackLeft, "50");
    lv_obj_set_style_text_font(ui_MotorBackLeft, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorBackRightPanel = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_MotorBackRightPanel, 200);
    lv_obj_set_height(ui_MotorBackRightPanel, 140);
    lv_obj_set_x(ui_MotorBackRightPanel, 4);
    lv_obj_set_y(ui_MotorBackRightPanel, 4);
    lv_obj_set_align(ui_MotorBackRightPanel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_MotorBackRightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorBackRightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorBackRightPanel, lv_color_hex(0x2D4467), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorBackRightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorBackRightPanel, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorBackRightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorBackRight = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_MotorBackRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorBackRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorBackRight, -55);
    lv_obj_set_y(ui_MotorBackRight, -40);
    lv_obj_set_align(ui_MotorBackRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_MotorBackRight, "10");
    lv_obj_set_style_text_font(ui_MotorBackRight, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplitBar = lv_bar_create(ui_Driver);
    lv_bar_set_range(ui_SplitBar, -100, 100);
    lv_bar_set_value(ui_SplitBar, 75, LV_ANIM_ON);
    lv_obj_set_width(ui_SplitBar, 800);
    lv_obj_set_height(ui_SplitBar, 208);
    lv_obj_set_align(ui_SplitBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SplitBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplitBar, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplitBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SplitBar, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SplitBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SplitBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SplitBar, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SplitBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplitBar, lv_color_hex(0xBEBEBE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplitBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SplitBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SplitBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SplitPanelTop = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_SplitPanelTop, 412);
    lv_obj_set_height(ui_SplitPanelTop, 130);
    lv_obj_set_x(ui_SplitPanelTop, 0);
    lv_obj_set_y(ui_SplitPanelTop, -86);
    lv_obj_set_align(ui_SplitPanelTop, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SplitPanelTop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SplitPanelTop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplitPanelTop, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplitPanelTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SplitPanelTop, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SplitPanelTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplitPanelBottom = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_SplitPanelBottom, 412);
    lv_obj_set_height(ui_SplitPanelBottom, 130);
    lv_obj_set_x(ui_SplitPanelBottom, 0);
    lv_obj_set_y(ui_SplitPanelBottom, 86);
    lv_obj_set_align(ui_SplitPanelBottom, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SplitPanelBottom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SplitPanelBottom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SplitPanelBottom, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplitPanelBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SplitPanelBottom, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SplitPanelBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplitString = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_SplitString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplitString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SplitString, 0);
    lv_obj_set_y(ui_SplitString, 88);
    lv_obj_set_align(ui_SplitString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SplitString, "+5.056");
    lv_obj_set_style_text_color(ui_SplitString, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SplitString, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SplitString, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SplitString, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SplitString, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplitTime = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_SplitTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplitTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SplitTime, 0);
    lv_obj_set_y(ui_SplitTime, -88);
    lv_obj_set_align(ui_SplitTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SplitTime, "1:32:2479");
    lv_obj_set_style_text_color(ui_SplitTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SplitTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SplitTime, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SplitTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SplitTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Driver);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -195);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "80 km/h");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriverLightUp = lv_obj_create(ui_Driver);
    lv_obj_set_width(ui_DriverLightUp, 800);
    lv_obj_set_height(ui_DriverLightUp, 480);
    lv_obj_set_align(ui_DriverLightUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DriverLightUp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DriverLightUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DriverLightUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DriverLightUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriverLightUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DriverLightUp, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DriverLightUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DriverLightUp, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Driver, ui_event_Driver, LV_EVENT_ALL, NULL);

}
