// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ts23_dash_03

#include "backend.hpp"
#include "../ui.h"

void ui_Diagnostics_screen_init(void)
{
    ui_Diagnostics = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Diagnostics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Division = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_Division, 8);
    lv_obj_set_height(ui_Division, 480);
    lv_obj_set_x(ui_Division, -396);
    lv_obj_set_y(ui_Division, 0);
    lv_obj_set_align(ui_Division, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Division, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Division, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Division, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Division, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Division, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Division, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Division, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Division, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiagnosticLightUp = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_DiagnosticLightUp, 792);
    lv_obj_set_height(ui_DiagnosticLightUp, 480);
    lv_obj_set_x(ui_DiagnosticLightUp, 4);
    lv_obj_set_y(ui_DiagnosticLightUp, 0);
    lv_obj_set_align(ui_DiagnosticLightUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DiagnosticLightUp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DiagnosticLightUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DiagnosticLightUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DiagnosticLightUp, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DiagnosticLightUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DiagnosticLightUp, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DiagnosticLightUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DiagnosticLightUp, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitlePanel = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_TitlePanel, 222);
    lv_obj_set_height(ui_TitlePanel, 78);
    lv_obj_set_x(ui_TitlePanel, 6);
    lv_obj_set_y(ui_TitlePanel, -2);
    lv_obj_clear_flag(ui_TitlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TitlePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitlePanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TitlePanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TitlePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title, 28);
    lv_obj_set_y(ui_Title, 20);
    lv_label_set_text(ui_Title, "Diagnostics");
    lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Watts = lv_arc_create(ui_Diagnostics);
    lv_obj_set_width(ui_Watts, 194);
    lv_obj_set_height(ui_Watts, 188);
    lv_obj_set_x(ui_Watts, 22);
    lv_obj_set_y(ui_Watts, 84);
    lv_arc_set_value(ui_Watts, 10);
    lv_arc_set_bg_angles(ui_Watts, 120, 300);
    lv_arc_set_rotation(ui_Watts, 5);

    lv_obj_set_style_arc_color(ui_Watts, lv_color_hex(0xFFFA00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Watts, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Watts, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Watts, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Amps = lv_arc_create(ui_Diagnostics);
    lv_obj_set_width(ui_Amps, 194);
    lv_obj_set_height(ui_Amps, 188);
    lv_obj_set_x(ui_Amps, 22);
    lv_obj_set_y(ui_Amps, 84);
    lv_arc_set_value(ui_Amps, 50);
    lv_arc_set_bg_angles(ui_Amps, 60, 145);
    lv_arc_set_mode(ui_Amps, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_Amps, 270);

    lv_obj_set_style_bg_color(ui_Amps, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Amps, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcPanel = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_ArcPanel, 100);
    lv_obj_set_height(ui_ArcPanel, 41);
    lv_obj_set_x(ui_ArcPanel, -284);
    lv_obj_set_y(ui_ArcPanel, -82);
    lv_obj_set_align(ui_ArcPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ArcPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcPanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcPanel, lv_color_hex(0x2F3237), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ArcPanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WattsString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_WattsString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WattsString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WattsString, -285);
    lv_obj_set_y(ui_WattsString, -80);
    lv_obj_set_align(ui_WattsString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WattsString, "122 kW");
    lv_obj_set_style_text_color(ui_WattsString, lv_color_hex(0xFFFA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WattsString, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WattsString, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpsString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AmpsString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpsString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AmpsString, -285);
    lv_obj_set_y(ui_AmpsString, -46);
    lv_obj_set_align(ui_AmpsString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AmpsString, "20 A");
    lv_obj_set_style_text_color(ui_AmpsString, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AmpsString, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AmpsString, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorPanel = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorPanel, 222);
    lv_obj_set_height(ui_AccumulatorPanel, 206);
    lv_obj_set_x(ui_AccumulatorPanel, 6);
    lv_obj_set_y(ui_AccumulatorPanel, 278);
    lv_obj_clear_flag(ui_AccumulatorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AccumulatorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccumulatorPanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccumulatorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AccumulatorPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AccumulatorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Accumulator_Title = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_Accumulator_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accumulator_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accumulator_Title, -284);
    lv_obj_set_y(ui_Accumulator_Title, 58);
    lv_obj_set_align(ui_Accumulator_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accumulator_Title, "Accumulator");
    lv_obj_set_style_text_font(ui_Accumulator_Title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorTempBar = lv_bar_create(ui_Diagnostics);
    lv_bar_set_value(ui_AccumulatorTempBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_AccumulatorTempBar, 138);
    lv_obj_set_height(ui_AccumulatorTempBar, 20);
    lv_obj_set_x(ui_AccumulatorTempBar, -306);
    lv_obj_set_y(ui_AccumulatorTempBar, 116);
    lv_obj_set_align(ui_AccumulatorTempBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AccumulatorTempBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccumulatorTempBar, lv_color_hex(0x2F3237), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccumulatorTempBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AccumulatorTempBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AccumulatorTempTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorTempTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccumulatorTempTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccumulatorTempTitle, -328);
    lv_obj_set_y(ui_AccumulatorTempTitle, 91);
    lv_obj_set_align(ui_AccumulatorTempTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccumulatorTempTitle, "Temperature");
    lv_obj_set_style_text_font(ui_AccumulatorTempTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorTempUnit = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorTempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccumulatorTempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccumulatorTempUnit, -188);
    lv_obj_set_y(ui_AccumulatorTempUnit, 116);
    lv_obj_set_align(ui_AccumulatorTempUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccumulatorTempUnit, "C");
    lv_obj_set_style_text_font(ui_AccumulatorTempUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorTempString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorTempString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccumulatorTempString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccumulatorTempString, -214);
    lv_obj_set_y(ui_AccumulatorTempString, 116);
    lv_obj_set_align(ui_AccumulatorTempString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccumulatorTempString, "95");
    lv_obj_set_style_text_font(ui_AccumulatorTempString, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorVoltageTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorVoltageTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccumulatorVoltageTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccumulatorVoltageTitle, -346);
    lv_obj_set_y(ui_AccumulatorVoltageTitle, 163);
    lv_obj_set_align(ui_AccumulatorVoltageTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccumulatorVoltageTitle, "Voltage");
    lv_obj_set_style_text_font(ui_AccumulatorVoltageTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorVoltageBar = lv_bar_create(ui_Diagnostics);
    lv_bar_set_value(ui_AccumulatorVoltageBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_AccumulatorVoltageBar, 138);
    lv_obj_set_height(ui_AccumulatorVoltageBar, 20);
    lv_obj_set_x(ui_AccumulatorVoltageBar, -306);
    lv_obj_set_y(ui_AccumulatorVoltageBar, 188);
    lv_obj_set_align(ui_AccumulatorVoltageBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AccumulatorVoltageBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccumulatorVoltageBar, lv_color_hex(0x2F3237), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccumulatorVoltageBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AccumulatorVoltageBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AccumulatorVoltageUnit = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorVoltageUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccumulatorVoltageUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccumulatorVoltageUnit, -188);
    lv_obj_set_y(ui_AccumulatorVoltageUnit, 188);
    lv_obj_set_align(ui_AccumulatorVoltageUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccumulatorVoltageUnit, "V");
    lv_obj_set_style_text_font(ui_AccumulatorVoltageUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccumulatorVoltageString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_AccumulatorVoltageString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccumulatorVoltageString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccumulatorVoltageString, -214);
    lv_obj_set_y(ui_AccumulatorVoltageString, 188);
    lv_obj_set_align(ui_AccumulatorVoltageString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccumulatorVoltageString, "95");
    lv_obj_set_style_text_font(ui_AccumulatorVoltageString, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorPanel = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorPanel, 222);
    lv_obj_set_height(ui_MotorPanel, 206);
    lv_obj_set_x(ui_MotorPanel, 226);
    lv_obj_set_y(ui_MotorPanel, 74);
    lv_obj_clear_flag(ui_MotorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorPanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorTitle, -68);
    lv_obj_set_y(ui_MotorTitle, -148);
    lv_obj_set_align(ui_MotorTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorTitle, "Motor");
    lv_obj_set_style_text_font(ui_MotorTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorSpeedTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorSpeedTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorSpeedTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorSpeedTitle, -110);
    lv_obj_set_y(ui_MotorSpeedTitle, -114);
    lv_obj_set_align(ui_MotorSpeedTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorSpeedTitle, "Max Speed: ");
    lv_obj_set_style_text_font(ui_MotorSpeedTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorSpeedString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorSpeedString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorSpeedString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorSpeedString, -24);
    lv_obj_set_y(ui_MotorSpeedString, -114);
    lv_obj_set_align(ui_MotorSpeedString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorSpeedString, "120 km/h");
    lv_obj_set_style_text_font(ui_MotorSpeedString, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorPowerTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorPowerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorPowerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorPowerTitle, -112);
    lv_obj_set_y(ui_MotorPowerTitle, -84);
    lv_obj_set_align(ui_MotorPowerTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorPowerTitle, "Max Power:");
    lv_obj_set_style_text_font(ui_MotorPowerTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorPowerString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorPowerString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorPowerString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorPowerString, -30);
    lv_obj_set_y(ui_MotorPowerString, -84);
    lv_obj_set_align(ui_MotorPowerString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorPowerString, "122 kW");
    lv_obj_set_style_text_font(ui_MotorPowerString, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorRpmTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorRpmTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorRpmTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorRpmTitle, -119);
    lv_obj_set_y(ui_MotorRpmTitle, -54);
    lv_obj_set_align(ui_MotorRpmTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorRpmTitle, "Max RPM:");
    lv_obj_set_style_text_font(ui_MotorRpmTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorRpmString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_MotorRpmString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorRpmString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorRpmString, -24);
    lv_obj_set_y(ui_MotorRpmString, -54);
    lv_obj_set_align(ui_MotorRpmString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorRpmString, "100 RPM");
    lv_obj_set_style_text_font(ui_MotorRpmString, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatePanel = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_StatePanel, 581);
    lv_obj_set_height(ui_StatePanel, 78);
    lv_obj_set_x(ui_StatePanel, 226);
    lv_obj_set_y(ui_StatePanel, -2);
    lv_obj_clear_flag(ui_StatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatePanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatePanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_StateTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateTitle, -120);
    lv_obj_set_y(ui_StateTitle, -204);
    lv_obj_set_align(ui_StateTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateTitle, "State:");
    lv_obj_set_style_text_font(ui_StateTitle, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_StateString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateString, -44);
    lv_obj_set_y(ui_StateString, -204);
    lv_obj_set_align(ui_StateString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateString, "201");
    lv_obj_set_style_text_font(ui_StateString, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateDivide = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_StateDivide, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateDivide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateDivide, -10);
    lv_obj_set_y(ui_StateDivide, -204);
    lv_obj_set_align(ui_StateDivide, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateDivide, "-");
    lv_obj_set_style_text_font(ui_StateDivide, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateDescription = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_StateDescription, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateDescription, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateDescription, 400);
    lv_obj_set_y(ui_StateDescription, 26);
    lv_label_set_text(ui_StateDescription, "RTD");
    lv_obj_set_style_text_align(ui_StateDescription, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StateDescription, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGBTPanel = lv_obj_create(ui_Diagnostics);
    lv_obj_set_width(ui_IGBTPanel, 222);
    lv_obj_set_height(ui_IGBTPanel, 84);
    lv_obj_set_x(ui_IGBTPanel, 446);
    lv_obj_set_y(ui_IGBTPanel, 74);
    lv_obj_clear_flag(ui_IGBTPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IGBTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IGBTPanel, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGBTPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IGBTPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IGBTPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGBTTitle = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_IGBTTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IGBTTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IGBTTitle, 155);
    lv_obj_set_y(ui_IGBTTitle, -148);
    lv_obj_set_align(ui_IGBTTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IGBTTitle, "IGBT Temp");
    lv_obj_set_style_text_font(ui_IGBTTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGBTString = lv_label_create(ui_Diagnostics);
    lv_obj_set_width(ui_IGBTString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IGBTString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IGBTString, 136);
    lv_obj_set_y(ui_IGBTString, -112);
    lv_obj_set_align(ui_IGBTString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IGBTString, "120");
    lv_obj_set_style_text_font(ui_IGBTString, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Diagnostics, ui_event_Diagnostics, LV_EVENT_ALL, NULL);

}
