// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ts23_dash_03

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Driver
void ui_Driver_screen_init(void);
void ui_event_Driver(lv_event_t * e);
lv_obj_t * ui_Driver;
lv_obj_t * ui_MotorFrontLeftPanel;
lv_obj_t * ui_MotorFrontLeft;
lv_obj_t * ui_MotorFrontRightPanel;
lv_obj_t * ui_MotorFrontRight;
lv_obj_t * ui_MotorBackLeftPanel;
lv_obj_t * ui_MotorBackLeft;
lv_obj_t * ui_MotorBackRightPanel;
lv_obj_t * ui_MotorBackRight;
lv_obj_t * ui_SplitBar;
lv_obj_t * ui_SplitPanelTop;
lv_obj_t * ui_SplitPanelBottom;
lv_obj_t * ui_SplitString;
lv_obj_t * ui_SplitTime;
lv_obj_t * ui_Label1;
lv_obj_t * ui_DriverLightUp;

// SCREEN: ui_Diagnostics
void ui_Diagnostics_screen_init(void);
void ui_event_Diagnostics(lv_event_t * e);
lv_obj_t * ui_Diagnostics;
lv_obj_t * ui_Division;
lv_obj_t * ui_DiagnosticLightUp;
lv_obj_t * ui_TitlePanel;
lv_obj_t * ui_Title;
lv_obj_t * ui_Watts;
lv_obj_t * ui_Amps;
lv_obj_t * ui_ArcPanel;
lv_obj_t * ui_WattsString;
lv_obj_t * ui_AmpsString;
lv_obj_t * ui_AccumulatorPanel;
lv_obj_t * ui_Accumulator_Title;
lv_obj_t * ui_AccumulatorTempBar;
lv_obj_t * ui_AccumulatorTempTitle;
lv_obj_t * ui_AccumulatorTempUnit;
lv_obj_t * ui_AccumulatorTempString;
lv_obj_t * ui_AccumulatorVoltageTitle;
lv_obj_t * ui_AccumulatorVoltageBar;
lv_obj_t * ui_AccumulatorVoltageUnit;
lv_obj_t * ui_AccumulatorVoltageString;
lv_obj_t * ui_MotorPanel;
lv_obj_t * ui_MotorTitle;
lv_obj_t * ui_MotorSpeedTitle;
lv_obj_t * ui_MotorSpeedString;
lv_obj_t * ui_MotorPowerTitle;
lv_obj_t * ui_MotorPowerString;
lv_obj_t * ui_MotorRpmTitle;
lv_obj_t * ui_MotorRpmString;
lv_obj_t * ui_StatePanel;
lv_obj_t * ui_StateTitle;
lv_obj_t * ui_StateString;
lv_obj_t * ui_StateDivide;
lv_obj_t * ui_StateDescription;
lv_obj_t * ui_IGBTPanel;
lv_obj_t * ui_IGBTTitle;
lv_obj_t * ui_IGBTString;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Driver(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Diagnostics, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
    }
}
void ui_event_Diagnostics(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Driver, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Driver_screen_init();
    ui_Diagnostics_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Driver);
}
