// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ts23_dash_03

#ifndef _TS23_DASH_03_UI_H
#define _TS23_DASH_03_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Driver
void ui_Driver_screen_init(void);
void ui_event_Driver(lv_event_t * e);
extern lv_obj_t * ui_Driver;
extern lv_obj_t * ui_MotorFrontLeftPanel;
extern lv_obj_t * ui_MotorFrontLeft;
extern lv_obj_t * ui_MotorFrontRightPanel;
extern lv_obj_t * ui_MotorFrontRight;
extern lv_obj_t * ui_MotorBackLeftPanel;
extern lv_obj_t * ui_MotorBackLeft;
extern lv_obj_t * ui_MotorBackRightPanel;
extern lv_obj_t * ui_MotorBackRight;
extern lv_obj_t * ui_SplitBar;
extern lv_obj_t * ui_SplitPanelTop;
extern lv_obj_t * ui_SplitPanelBottom;
extern lv_obj_t * ui_SplitString;
extern lv_obj_t * ui_SplitTime;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_DriverLightUp;
// SCREEN: ui_Diagnostics
void ui_Diagnostics_screen_init(void);
void ui_event_Diagnostics(lv_event_t * e);
extern lv_obj_t * ui_Diagnostics;
extern lv_obj_t * ui_Division;
extern lv_obj_t * ui_DiagnosticLightUp;
extern lv_obj_t * ui_TitlePanel;
extern lv_obj_t * ui_Title;
extern lv_obj_t * ui_Watts;
extern lv_obj_t * ui_Amps;
extern lv_obj_t * ui_ArcPanel;
extern lv_obj_t * ui_WattsString;
extern lv_obj_t * ui_AmpsString;
extern lv_obj_t * ui_AccumulatorPanel;
extern lv_obj_t * ui_Accumulator_Title;
extern lv_obj_t * ui_AccumulatorTempBar;
extern lv_obj_t * ui_AccumulatorTempTitle;
extern lv_obj_t * ui_AccumulatorTempUnit;
extern lv_obj_t * ui_AccumulatorTempString;
extern lv_obj_t * ui_AccumulatorVoltageTitle;
extern lv_obj_t * ui_AccumulatorVoltageBar;
extern lv_obj_t * ui_AccumulatorVoltageUnit;
extern lv_obj_t * ui_AccumulatorVoltageString;
extern lv_obj_t * ui_MotorPanel;
extern lv_obj_t * ui_MotorTitle;
extern lv_obj_t * ui_MotorSpeedTitle;
extern lv_obj_t * ui_MotorSpeedString;
extern lv_obj_t * ui_MotorPowerTitle;
extern lv_obj_t * ui_MotorPowerString;
extern lv_obj_t * ui_MotorRpmTitle;
extern lv_obj_t * ui_MotorRpmString;
extern lv_obj_t * ui_StatePanel;
extern lv_obj_t * ui_StateTitle;
extern lv_obj_t * ui_StateString;
extern lv_obj_t * ui_StateDivide;
extern lv_obj_t * ui_StateDescription;
extern lv_obj_t * ui_IGBTPanel;
extern lv_obj_t * ui_IGBTTitle;
extern lv_obj_t * ui_IGBTString;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
